#include <ppm_reader.h>
#include <samc21.h>
#include <gpio.h>

/*
PA12 RADIO4 EXT-12
PA13 RADIO3 EXT-13
PA14 RADIO2 EXT-14
PA15 RADIO1 EXT-15
PA4 RADIO8 EXT-4
PA5 RADIO7 EXT-5
PA6 RADIO6 EXT-6
PA7 RADIO5 EXT-5
*/

void init_ppm_pin (void );

volatile uint32_t ppm_width_raw[8];

void TCC0_Handler () {
	if (TCC0->INTFLAG.bit.OVF) {
		TCC0->INTFLAG.reg = TCC_INTFLAG_OVF;
	}

	if (TCC0->INTFLAG.bit.TRG) {
		TCC0->INTFLAG.reg = TCC_INTFLAG_TRG;
	}

	if (TCC0->INTFLAG.bit.MC2) {
		TCC0->INTFLAG.reg = TCC_INTFLAG_MC2;
	}
}

void TCC1_Handler () {
	if (TCC1->INTFLAG.bit.OVF) {
		TCC1->INTFLAG.reg = TCC_INTFLAG_OVF;
	}
}

void TCC2_Handler () {
	if (TCC2->INTFLAG.bit.OVF) {
		TCC2->INTFLAG.reg = TCC_INTFLAG_OVF;
	}
}

void init_ppm_reader () {
	init_ppm_pin ();

	MCLK->APBCMASK.bit.TCC0_ = 1;
	MCLK->APBCMASK.bit.TCC1_ = 1;
	MCLK->APBCMASK.bit.TCC2_ = 1;

	// TCC(0, 1), (2) => 8MHZ CLOCK
	GCLK->PCHCTRL[TCC0_GCLK_ID].bit.GEN = 8;
	GCLK->PCHCTRL[TCC0_GCLK_ID].bit.CHEN = 1;
	GCLK->PCHCTRL[TCC2_GCLK_ID].bit.GEN = 8;
	GCLK->PCHCTRL[TCC2_GCLK_ID].bit.CHEN = 1;

	TCC0->CTRLA.bit.SWRST = 1;
	while (TCC0->CTRLA.bit.SWRST);

	TCC1->CTRLA.bit.SWRST = 1;
	while (TCC1->CTRLA.bit.SWRST);

	TCC2->CTRLA.bit.SWRST = 1;
	while (TCC2->CTRLA.bit.SWRST);

	TCC0->CTRLA.bit.CPTEN0 = 1;
	TCC0->CTRLA.bit.CPTEN1 = 1;
	TCC0->CTRLA.bit.CPTEN2 = 1;
	TCC0->CTRLA.bit.CPTEN3 = 1;
	TCC1->CTRLA.bit.CPTEN0 = 1;
	TCC1->CTRLA.bit.CPTEN1 = 1;
	TCC2->CTRLA.bit.CPTEN0 = 1;
	TCC2->CTRLA.bit.CPTEN1 = 1;

	// 8Mhz / 8 = 1MHz (1 lsb = 1uS)
	TCC0->CTRLA.bit.PRESCALER = TCC_CTRLA_PRESCALER_DIV8_Val;
	TCC0->CTRLA.bit.RESOLUTION = TCC_CTRLA_RESOLUTION_NONE_Val;
	TCC1->CTRLA.bit.PRESCALER = TCC_CTRLA_PRESCALER_DIV8_Val;
	TCC1->CTRLA.bit.RESOLUTION = TCC_CTRLA_RESOLUTION_NONE_Val;
	TCC2->CTRLA.bit.PRESCALER = TCC_CTRLA_PRESCALER_DIV8_Val;
	TCC2->CTRLA.bit.RESOLUTION = TCC_CTRLA_RESOLUTION_NONE_Val;

	TCC0->CTRLBCLR.bit.DIR = 1;
	TCC0->CTRLBSET.bit.ONESHOT = 1;
	TCC0->PERBUF.bit.PERBUF = TCC_PERIOD_US - 1;
	TCC0->PER.bit.PER = TCC_PERIOD_US - 1;
	TCC1->CTRLBCLR.bit.DIR = 1;
	TCC1->CTRLBSET.bit.ONESHOT = 1;
	TCC1->PERBUF.bit.PERBUF = TCC_PERIOD_US - 1;
	TCC1->PER.bit.PER = TCC_PERIOD_US - 1;
	TCC2->CTRLBCLR.bit.DIR = 1;
	TCC2->CTRLBSET.bit.ONESHOT = 1;
	TCC2->PERBUF.bit.PERBUF = TCC_PERIOD_US - 1;
	TCC2->PER.bit.PER = TCC_PERIOD_US - 1;

	TCC0->EVCTRL.reg = \
		TCC_EVCTRL_MCEI0 | TCC_EVCTRL_MCEI1 | TCC_EVCTRL_MCEI2 | TCC_EVCTRL_MCEI3 | \
		TCC_EVCTRL_MCEO0 | TCC_EVCTRL_MCEO1 | TCC_EVCTRL_MCEO2 | TCC_EVCTRL_MCEO3;
	 TCC1->EVCTRL.reg = TCC_EVCTRL_MCEI0 | TCC_EVCTRL_MCEI1 | TCC_EVCTRL_MCEO0 | TCC_EVCTRL_MCEO1;
	 TCC2->EVCTRL.reg = TCC_EVCTRL_MCEI0 | TCC_EVCTRL_MCEI1 | TCC_EVCTRL_MCEO0 | TCC_EVCTRL_MCEO1;

	TCC0->EVCTRL.bit.TCEI0 = 1;
	TCC0->EVCTRL.bit.EVACT0 = TCC_EVCTRL_EVACT0_RETRIGGER_Val;
	TCC1->EVCTRL.bit.TCEI0 = 1;
	TCC1->EVCTRL.bit.EVACT0 = TCC_EVCTRL_EVACT0_RETRIGGER_Val;
	TCC2->EVCTRL.bit.TCEI0 = 1;
	TCC2->EVCTRL.bit.EVACT0 = TCC_EVCTRL_EVACT0_RETRIGGER_Val;

	TCC0->INTENSET.bit.OVF = 1;
	TCC1->INTENSET.bit.OVF = 1;
	TCC2->INTENSET.bit.OVF = 1;

	TCC0->CTRLA.bit.ENABLE = 1;
	TCC1->CTRLA.bit.ENABLE = 1;
	TCC2->CTRLA.bit.ENABLE = 1;
}

void init_ppm_pin () {
	//PA12 - PA15
	PORT->Group[0].PMUX[6].bit.PMUXE = 0; //PA12
	PORT->Group[0].PMUX[6].bit.PMUXO = 0; //PA13
	PORT->Group[0].PMUX[7].bit.PMUXE = 0; //PA14
	PORT->Group[0].PMUX[7].bit.PMUXO = 0; //PA15
	for (uint8_t pin = 12; pin <= 15; pin++) {
		PORT->Group[0].PINCFG[pin].bit.PMUXEN = 1;
	}

	//PA4 - PA7
	PORT->Group[0].PMUX[2].bit.PMUXE = 0;
	PORT->Group[0].PMUX[2].bit.PMUXO = 0;
	PORT->Group[0].PMUX[3].bit.PMUXE = 0;
	PORT->Group[0].PMUX[3].bit.PMUXO = 0;
	for (uint8_t pin = 4; pin <= 7; pin++) {
		PORT->Group[0].PINCFG[pin].bit.PMUXEN = 1;
	}
}